spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 20
      max-lifetime: 600000
      connection-timeout: 15000
      validation-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
sentry:
  dsn:
logging:
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/app-%d{yyyy-MM-dd_HH-mm}.%i.log
      max-file-size: 10MB

